# Generated by Django 5.1.2 on 2025-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_lineprediction_characterimage_toppredictions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toppredictions",
            name="image",
        ),
        migrations.AddField(
            model_name="toppredictions",
            name="position",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CharacterImage",
        ),
    ]
