# Generated by Django 5.1.2 on 2025-01-26 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0003_remove_toppredictions_image_toppredictions_position_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LinePrediction",
            new_name="CodeBlockPrediction",
        ),
        migrations.RenameField(
            model_name="codeblockprediction",
            old_name="predicted_line",
            new_name="predicted_text",
        ),
        migrations.RenameField(
            model_name="toppredictions",
            old_name="line",
            new_name="code_block",
        ),
    ]
