# Generated by Django 4.1.13 on 2025-04-11 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_rename_lineprediction_codeblockprediction_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
