# Generated by Django 5.1.2 on 2025-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_notebook_remove_characterprediction_prediction_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="notebook_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
