services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"

    volumes:
      - ./backend/:/backend/

    env_file:
      - .env
