services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/backend/
    environment:
      FLASK_ENV: "development"
  # client:
  #   build:
  #     context: ./frontend
  #     dockerfile: dockerfile
  #   ports:
  #     "3000:3000"