site_name: Enscribe Documentation

theme:
  name: "material"

nav:
  - Overview: index.md
  - Models: models.md
  - Utils: utils.md
  - Views: views.md
  - Frontend: frontend.md

plugins:
  - monorepo
  - mkdocstrings
