FROM python:3.11-slim

WORKDIR /backend

COPY . .

RUN pip install poetry

RUN poetry config virtualenvs.create false

RUN poetry install

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]