FROM python:3.11-slim

WORKDIR /backend

RUN pip install poetry

RUN apt-get update && apt-get install -y default-libmysqlclient-dev pkg-config build-essential && rm -rf /var/lib/apt/lists/*

COPY . .

RUN chmod +x ./entrypoint.sh

RUN poetry config virtualenvs.create false

RUN poetry install

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]
