FROM python:3.11-alpine

WORKDIR /backend

COPY .. .

RUN pip install poetry

RUN poetry config virtualenvs.create false

RUN poetry install

CMD [ "poetry", "run", "python", "./manage.py", "runserver", "0.0.0.0:5000"]

