name: Build, Test and Publish Image

on:
  push:
    branches: [main, dev, 3-setup-deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: |
          if ["${{github.ref}}" == "refs/heads/main"]; then
            echo "REPO_LC=enscribe" >>${GITHUB_ENV}
          else
            echo "REPO_LC=enscribe-dev" >>${{GITHUB_ENV}}
          fi
        env:
          REPO: '${{ github.repository }}'

      - name: Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest


# name: Build, Test and Publish Image

# on: workflow_dispatch

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#         contents: read
#         packages: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#         with:
#           platforms: linux/amd64, linux/arm64

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Lowercase repo name
#         run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
#         env:
#           REPO: '${{ github.repository }}'

#       - name: Push image to GHCR
#         uses: docker/build-push-action@v5
#         with:
#           context: ./sarahdoesenglish
#           push: true
#           tags: ghcr.io/${{ env.REPO_LC }}:latest
#           platforms: linux/amd64, linux/arm64